name: Continuos integration
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Descargando el proyecto
      - name: Instalando Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
        name: Instalando Gradle
      - name: Run build project
        run: ./gradlew build
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Push Docker image
        with:
          image: danielsabana/patrones
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: danielsabana
          password: ${{ secrets.DOCKER_PASSWORD }}